### ISSUE TITLE
Unclear usage in development cycle

### ISSUE THREAD

**Issue by hintjens** [mafintosh/prebuild#101]
I'm having difficulty understanding how to properly use `prebuild` during development of a binding.

* `prebuild` reads `.prebuildrc` but does not recompile my code when `binding.cc` changes.
* `prebuild --all` builds all versions but does not recompile my code when `binding.cc` changes.
* `prebuild --compile` *does* recompile my code when `binding.cc` changes but builds the current version of node.js (ignoring what's in .prebuildrc)

**Comment by ralphtheninja** [comment]
This is when using `node-ninja` right?

**Comment by ralphtheninja** [comment]
Afaict there's no difference between `prebuild --all` and `prebuild --compile` for _leveldown_, apart from the fact that `--compile` compiles for current target (essentially just identical to `node-gyp rebuild`) and `--all` compiles for all versions (and does the bundling)

**Comment by hintjens** [comment]
@ralphtheninja it is, though I didn't think that would affect things. Clearly it's affected by the incremental builds... yet when I run `node-gyp build` it does recognize changed files. Prebuild isn't even getting that far. I *think* it's skipping because there's existing packages. If I `rm prebuilds/*` beforehand, it works as expected.

Perhaps when doing incremental builds / using `node-ninja`, it could rebuild the packages each time? Shall I make this change?

If `prebuild --compile` means 'build for current target' then it could have a better name. Perhaps `--current`.... to match `--all`.

**Comment by ralphtheninja** [comment]
> I think it's skipping because there's existing packages. If I rm prebuilds/* beforehand, it works as expected. Perhaps when doing incremental builds / using node-ninja, it could rebuild the packages each time? Shall I make this change?

That sort of makes sense. Why build it again if it's already built? (Assuming this happens because of the skip step that is).

> If prebuild --compile means 'build for current target' then it could have a better name. Perhaps --current.... to match --all.

I agree this is confusing. There's more to it. `prebuild --compile` === `node-gyp rebuild`, but `prebuild --all` does much more than *just* compiling the code. I would much rather remove the `--compile` variant completely.

**Comment by ralphtheninja** [comment]
Obviously you want to rebuild things, that was a quick answer and I'm in a hurry, sorry :)

**Comment by hintjens** [comment]
Removing `--compile` would be fine. All I really wanted was (a) a way to rebuild when I change binding.cc, and (b) predictability about which ABI versions get built. I can get (a) by deleting the prebuilds folder. We can get (b) by removing `--compile`.

**Comment by hintjens** [comment]
So my question: shall I look at ignoring `prebuilds` when doing incremental (node-ninja) builds?

**Comment by hintjens** [comment]
To be clear, my work cycle is:

* Edit my binding.cc
* Build
* Test

I'm starting to realize that using `prebuild` for this is stupid... my bad. I'll use `node-ninja` directly, it's simpler and cleaner.

Closing the issue, thanks a lot for answering.

**Comment by mafintosh** [comment]
i use node-gyp directly when developing as well. i think that flow is a lot
easier than using prebuild --compile etc

**Comment by ralphtheninja** [comment]
> I'm starting to realize that using prebuild for this is stupid... my bad. I'll use node-ninja directly, it's simpler and cleaner.

No worries. It brought up something that was confusing. I vote for removing `--compile` completely anyway, since you can just use `node-gyp` or `node-ninja` directly.

**Comment by hintjens** [comment]
+1

On Thu, Feb 25, 2016 at 10:26 PM, Lars-Magnus Skog <notifications@github.com
