### ISSUE TITLE
Package size

### ISSUE THREAD

**Issue by mathiask88** [mafintosh/prebuild#105]
Prebuild is 14 times the size of my addon. Isn't it possible to exclude e.g. ninja dependency or even node-gyp by using the version that ships with node.js to make the shipped addon a bit lighter? Most of the time the end user won't even need these because the aim is to get prebuilds :) What if the node-ninja and node-gyp dependencies that are needed to prebuild the binaries were devDependencies or maybe split the module one for the developer to prebuild and one to include in the module dependency tree?

**Comment by ralphtheninja** [comment]
I can understand your pain and we should probably do _something_ about it, I'm not exactly sure what though, but lets figure something out.

The reasons node-gyp (and node-ninja) are dependencies is that we want to be sure headers are downloaded properly (in node-gyp 3+ iirc) for the node version you are building for.

devDependency is not an option since you would only get those dependencies if you installed from source and not from npm. I think splitting the module is the way to go here.

**Comment by mathiask88** [comment]
Yes, I think splitting would be the smartest option. So developers could easily install `prebuild` as a global module to manage their prebuilds and ship their addon with a lightweight `prebuild-client` or however named that just downloads the binary and if none are available then just use the npm's build functionality like without prebuild.

**Comment by ralphtheninja** [comment]
cc @mafintosh @juliangruber @brett19 @hintjens

**Comment by hintjens** [comment]
I like the idea of splitting into booster and capsule. I've no problem with
large dependencies during development yet it is uncomfortable to force this
onto the user of a native module.

FWIW node-ninja and node-gyp share the same dependencies at present.

**Comment by juliangruber** [comment]
+1 to a lightweight prebuild client. i don't care too much about dependency sizes either, downloading 100 modules seems faster than building 1.

**Comment by mafintosh** [comment]
+1 on having a small install module.

**Comment by mathiask88** [comment]
I don't have much time ATM but what do u think of this? https://github.com/mathiask88/prebuild/tree/slimming

**Comment by ralphtheninja** [comment]
> I don't have much time ATM but what do u think of this? https://github.com/mathiask88/prebuild/tree/slimming

I did a quick check and it looks really good. Only one thing though, does `cmd1 || cmd2` work on windows?

**Comment by mathiask88** [comment]
>Only one thing though, does cmd1 || cmd2 work on windows?

Yes, https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/ntcmds_shelloverview.mspx?mfr=true 
I dont know if `..|| node-gyp rebuild` is the best option. If npm ever bundles an other build system this won't work anymore, but I don't know a better solution. And of course tests, readme and such are not updated yet.

**Comment by mathiask88** [comment]
At second glance I think we should omit the `--download`` because it is the main purpose and there should be an option that prevents downloading for people only trusting their compiler and the code they read :)

**Comment by juliangruber** [comment]
not everyone will have node-gyp installed, excluding this one is dangerous imo..it breaks the `just npm install it` promise.

**Comment by mathiask88** [comment]
@juliangruber Everyone who got npm got node-gyp because it is a bundled dependency. Did I miss something?

**Comment by juliangruber** [comment]
from https://github.com/nodejs/node-gyp/wiki/Updating-npm's-bundled-node-gyp:

> npm bundles its own, internal, copy of node-gyp. This internal copy is independent of any globally installed copy of node-gyp that you may have installed via npm install -g node-gyp.

> This means that while node-gyp doesn't get installed into your $PATH by default, npm still keeps its own copy to invoke when you attempt to npm install a native addon.

**Comment by juliangruber** [comment]
npm does have node-gyp as a dependency, but that doesn't mean it will be linked into `$PATH`, which is only the case if you `npm install -g node-gyp`

**Comment by mathiask88** [comment]
Yes, npm's node-gyp is not in the global PATH but npm looks also in it's own bin folder for commands used inside the script tag. I don't have node-gyp installed global and this works as expected.

**Comment by mathiask88** [comment]
@juliangruber Are you ok with this approach? Calling `node-gyp rebuild` is also the [default action](https://docs.npmjs.com/misc/scripts#default-values) in npm if there is a `binding.gyp` which will always be the case for native modules.

**Comment by juliangruber** [comment]
yup, sorry just reading up on this. I learned something new, thank you :) I'm fine with this

**Comment by mathiask88** [comment]
Ok cool. Then I will update the readme, add a `--no-prebuild` option to skip downloading prebuilds and have a look at the tests. Are you guys happy with the name `prebuild-client`? If so, can @mafintosh create a repo for this?

**Comment by mafintosh** [comment]
@mathiask88 i think `prebuild-install` is a bit cleaner as it mimicks the `--install` flag. still want me to make a repo?

**Comment by mathiask88** [comment]
Sure, I like `prebuild-install` :)

**Comment by mafintosh** [comment]
@mathiask88 done, https://github.com/mafintosh/prebuild-install - i've added you as owner

**Comment by mathiask88** [comment]
Thanks. I will crate a PR to review when I'm done.

**Comment by ralphtheninja** [comment]
> Thanks. I will crate a PR to review when I'm done.

:+1:

**Comment by mathiask88** [comment]
Shall I PR against this repo so you can see the changes better? We can close that PR after the review and just commit the changes over to `prebuild-install`.

**Comment by piranna** [comment]
@mathiask88, why the `--no-prebuild` argument? It's just the only reason of the module, so I think it doesn't make sense and should be removed...

**Comment by mathiask88** [comment]
@piranna Thought of people who want explicity build from source.

**Comment by piranna** [comment]
> @piranna Thought of people who want explicity build from source.

But then why to use `prebuild-install` in first place, then? Mostly it only just download and unpack a prebuild image, with `--no-prebuild` it becames a no-op...

**Comment by mathiask88** [comment]
The purpose was that addon authors can implement prebuild-install in their native module with
```
  "scripts": {
    "install": "prebuild-install -d || node-gyp rebuild"
  }
```
And then a user can do `npm install native-module --no-prebuild` to build from source.

**Comment by piranna** [comment]
Ok, I didn't considerate this corner case. I'm really interested on `prebuild-install` to use it on [nodeos-cross-toolchain](https://github.com/NodeOS/nodeos-cross-toolchain), specially the ability of not exec `node-gyp` automatically but instead allow to use `||` to define the module build process. If you need a beta-tester here I am ;-)

**Comment by mathiask88** [comment]
Anybody got some time to review? @ralphtheninja

**Comment by piranna** [comment]
Any update on this?

**Comment by ralphtheninja** [comment]
@piranna I have been busy with stuff, but on vacation now so hopefully will have some time to clean up some issues

@mathiask88 Mind pushing up your code to `prebuild-install`?

**Comment by piranna** [comment]
Ok, thank you. Yes, I'm mostly interested on `prebuil-install` and its feature of using a shell `or` to exec the build process... :-)

**Comment by mathiask88** [comment]
@ralphtheninja Done https://github.com/mafintosh/prebuild-install/tree/WIP You can also see the changes I made with reference to this repo here https://github.com/mathiask88/prebuild/commit/568a9605f42ec83561a00169d48fd13cf6e1e5f3

**Comment by piranna** [comment]
Is there any progress on using `prebuild-install` as dependency of this module?

**Comment by ralphtheninja** [comment]
> Is there any progress on using prebuild-install as dependency of this module?

Either that, or we remove it altogether and release a new major. I don't mind either way.

**Comment by piranna** [comment]
I didn't consider about removing it altogheter, but maybe it would be a good idea too, there could be development process that don't need the installer at all...
