### ISSUE TITLE
--download Invalid version number: 0.10.40,0.12.7,4.0.0

### ISSUE THREAD

**Issue by corbinu** [mafintosh/prebuild#106]
I am having some trouble upgrading to 4.1.0.

When running npm install (which triggers prebuild --download https://github.com/corbinu/couchnode/releases/download/v{version}/couchbase-v{version}-node-v{abi}-{platform}-{arch}.tar.gz)

I get the following error:

prebuild ERR! stack Error: Invalid version number: 0.10.40,0.12.7,4.0.0
prebuild ERR! stack     at getNodeDir (/Users/corbinu/Developer/git/couchnode/node_modules/node-gyp/lib/configure.js:69:25)

https://travis-ci.org/corbinu/couchnode/jobs/113306903

**Comment by ralphtheninja** [comment]
@corbinu Thanks for noticing this. Checking it out now.

**Comment by ralphtheninja** [comment]
@juliangruber You made some commits that changed from `process.version` to `rc.target`:

* https://github.com/mafintosh/prebuild/commit/1d2d76074124ba0abbde4dcd0729a2b88d79b349
* https://github.com/mafintosh/prebuild/commit/9b922361b1e98264183bf9fa40081c4a0c7ffa81

I guess this is for supporting the electron things. This goes bananas if you are doing either `prebuild --download` or `prebuild --install` _and_ if you have a `.prebuildrc` file similar to https://github.com/corbinu/couchnode/blob/5c39aab50653bd5dae7c2a77fe195915bab91dc1/.prebuildrc

How can we solve this without breaking your stuff that relies on `rc.target` being passed in?

**Comment by ralphtheninja** [comment]
@corbinu Ok, I just needed some rubber ducking. You need to change your `.prebuildrc` file to:

```
# abi 11             
prebuild[] = 0.10.40 
                     
# abi 14             
prebuild[] = 0.12.7  
                     
# abi 46             
prebuild[] = 4.0.0   
```

@juliangruber Nevermind :wink:

**Comment by ralphtheninja** [comment]
@corbinu Actually. Let me just make a PR to your repo.

**Comment by ralphtheninja** [comment]
https://github.com/corbinu/couchnode/pull/1

**Comment by mafintosh** [comment]
in general we should stop encouraging people to use .prebuildrc for anything other than the github token

**Comment by mafintosh** [comment]
... now that we have the great --all option :)

**Comment by corbinu** [comment]
All green now thanks guys!

**Comment by ralphtheninja** [comment]
:+1:

**Comment by ralphtheninja** [comment]
> in general we should stop encouraging people to use .prebuildrc for anything other than the github token

Sounds good. I'll make a PR on that.

**Comment by ralphtheninja** [comment]
https://github.com/mafintosh/prebuild/pull/107
