### ISSUE TITLE
Add url option for what clib

### ISSUE THREAD

**Issue by corbinu** [mafintosh/prebuild#108]
I am running into an issue where I have prebuild building a linux version. Which then when I try to install in https://github.com/mhart/alpine-node

Prebuild pulls the linux build thinking it is acceptable however alpine uses musl libc not gnu libc
http://www.musl-libc.org/faq.html

So the binary is incompatible. I am wondering if there is anyway to add a URL option that would also include the libc version so that I could set travis to build for both options and tag them separately.

Thanks!

**Comment by juliangruber** [comment]
we don't have that as an option yet but can easily add it. what do the other contributors think?

**Comment by corbinu** [comment]
Thanks. It looks like ldd could be used on linux to figure out what version of libc is available. Anything I can do to help let me know.

**Comment by ralphtheninja** [comment]
> we don't have that as an option yet but can easily add it. what do the other contributors think?

+1

@juliangruber We had a similar problem with leveldown-hyper and alpine at NowSecure

**Comment by juliangruber** [comment]
@ralphtheninja can you take this one?

**Comment by ralphtheninja** [comment]
@juliangruber Sorry that I haven't responded until now. Been busy with irl :/ I'll try looking in to it this week.

**Comment by corbinu** [comment]
@ralphtheninja I would be happy to take a crack at this if your busy. I am just wondering what you all think the best solution is. Given

1. This should only be an issue on Linux and BSD (only two OS I know of that Node supports might have different libc)
2. There is a default assumed libc for both
3. Node doesn't have the libc type in "process"
4. There does not seem to be a good terminal command I can find to say "what libc is this" (ldd appears to vary a lot even when it is normal glibc

I was thinking the best bet might just to be look for a LIBC env variable and if it is set make the upload/download URL allow that variable so the default template could become
`{name}-v{version}-node-v{abi}-{platform}{libc}-{arch}.tar.gz`

which makes it a nonbreaking change for the normal urls. I would then just issue a PR for the node alpine container to have ENV LIBC=musl This way I can do a separate CI prebuild in the alpine container and I would simply end up with two linux tars one the normal format and one with -linuxmusl-

Let me know if this sounds like a good solution

**Comment by ralphtheninja** [comment]
@corbinu Just hack something up and make a PR and then we can discuss and tweak it :)

**Comment by piranna** [comment]
Sorry for being late to the party, I missed this issue completely. Could this be ported to `prebuild-install`? This would make me things easier on NodeOS. Also, to check for the system default libc, I'm doing `readlink /lib/ld-linux.so.2 | grep musl`, this way I can be able to know if system libc is musl-based or not, for glibc it would be `gnu` instead.
