### ISSUE TITLE
prebuild ignores the Node.js version choosed through NVM 

### ISSUE THREAD

**Issue by luii** [mafintosh/prebuild#113]
on my main OS i got some strange errors (described [in here](https://github.com/NodeOS/NodeOS/issues/223#issuecomment-210084936) and i found out that prebuild is causing this error.
It downloads the wrong Module version of `fuse-bindings` (47 instead of 46).
I use the nodejs package (which is 5.10.1) in Arch and NVM alongisde

**Comment by lgeiger** [comment]
Since the linked issue is now resolved I think we can close this.
