### ISSUE TITLE
force compiling on electron abi=48

### ISSUE THREAD

**Issue by mafintosh** [mafintosh/prebuild#128]
Because of https://github.com/electron/electron/issues/5851 prebuilds are failing in a terrible way on latest electron (they'll usually load but strange bugs happen).

This is because the electron abi is pretending to be compatible with node when it currently isn't.
Is there anyway we can force compile when someone is trying to install a prebuild for electron to work around this?

**Comment by mafintosh** [comment]
Usually `--runtime=electron` is passed to npm when installing prebuilds for electron. Here is an example, https://github.com/juliangruber/dat-desktop/blob/master/package.json#L26. Should we check for that and `abi === 48` and force compiling as a workaround until they fix their bug?

**Comment by mafintosh** [comment]
Actually `abi === 48` and `version > 1.1.3` is when compiling needs to happen. What a mess...

**Comment by ralphtheninja** [comment]
> Actually abi === 48 and version > 1.1.3 is when compiling needs to happen. What a mess...

Ugh.

**Comment by ralphtheninja** [comment]
> Usually --runtime=electron is passed to npm when installing prebuilds for electron. Here is an example, https://github.com/juliangruber/dat-desktop/blob/master/package.json#L26. Should we check for that and abi === 48 and force compiling as a workaround until they fix their bug?

+1 Even though it's messy, it's better than crashing.

Is this something that can be fixed in electron while maintaining the same abi version?

**Comment by mafintosh** [comment]
No the problem is that electron is using the wrong abi. Hopefully they'll fix that soon

**Comment by rgbkrk** [comment]
Since they're not fixing it, can we switch to a "build for all electron releases" approach?
