### ISSUE TITLE
add support for --pkg-version

### ISSUE THREAD

**Issue by ralphtheninja** [mafintosh/prebuild#13]
Currently `prebuild` picks up the current version from `package.json`. This means that `package.json` always has to have the correct value, which might not always be the case.

Maybe you are building binaries from a QA/testing perspective, i.e. doing a debug build and sending off the resulting binaries to some test system before actually publishing the native module to npm.

E.g.:

```
$ cd a-native-module
$ git checkout <some-sha1-hash>
$ prebuild --version 3.1.1-alpha5 -t 2.5.0
$ scp -r prebuilds/*.tar.gz user@example.com:build-server/
..
```

**Comment by mafintosh** [comment]
:+1: ... we use `--version` to print out the prebuild version now though but we should support this

**Comment by mafintosh** [comment]
if the version flag has a value we could use it in the naming of the prebuild. and if it doesn't it would print out the prebuild version.

**Comment by ralphtheninja** [comment]
:+1:

**Comment by ralphtheninja** [comment]
Or  use `--pkg-version`?

**Comment by mafintosh** [comment]
yea that's probably better. then we could support `--pkg-name` and other ones as well

**Comment by ralphtheninja** [comment]
Closing. Lets wait for a real use case before adding.
