### ISSUE TITLE
prebuild --install defaults to compile on Yarn

### ISSUE THREAD

**Issue by mourner** [mafintosh/prebuild#132]
Yarn: https://code.facebook.com/posts/1840075619545360

If you install a native module with Yarn instead of NPM, `prebuild --install` in the module's install script will always default to compiling rather than downloading a suitable binary.

cc @mafintosh

**Comment by mafintosh** [comment]
any idea what we can do to support it?

**Comment by mourner** [comment]
> `--install` will download binaries when installing from npm and compile in other cases.

@mafintosh I'm not sure... How does `prebuild` detect if it's run by installing from NPM?

**Comment by mafintosh** [comment]
https://github.com/mafintosh/prebuild/blob/b020f36eab0f14dd40f4aff4ad9ae71f7b7148b5/bin.js#L48-L59 - if you can look what it looks like in the yarn case we can add a case for that

**Comment by mourner** [comment]
@mafintosh it looks like Yarn does not augment `package.json` at all upon install. So there's no `_from` attribute. So `!(typeof pkg._from === 'string')` evaluates to `false` so `prebuild` assumes it comes directly from Git rather than installed. Any ideas on how to detect this differently?

**Comment by mafintosh** [comment]
@mourner maybe yarn sets an env var or something? worst case we could look at process.argv i'm guessing.

**Comment by mourner** [comment]
@mafintosh I was looking at `process.env` too but it looks like there's nothing useful there. `process.argv` is probably not useful too because it doesn't contain package-specific info (e.g. if you just run `yarn install` to install dependencies, you can't tell from `process.argv` whether the native dep in `package.json` is a git SHA or a semver). Maybe I should submit an issue to Yarn and see if anyone has ideas...

**Comment by mafintosh** [comment]
@mourner good idea. i'm sure they are open to adding a env var

**Comment by mourner** [comment]
Submitted https://github.com/yarnpkg/yarn/issues/1050. Worst case, we'll have to calculate SHA1 of a zipped package and do a request to the NPM registry to compare, but this sounds really terrible.

**Comment by pi0** [comment]
Please checkout [YarNPM](https://github.com/pi0/yarnpm) :)

**Comment by mourner** [comment]
@pi0 it won't help solving this issue.

**Comment by piranna** [comment]
Shouldn't this be discussed on `prebuild-install` module instead?
