### ISSUE TITLE
Motivation (node-pre-gyp compare)

### ISSUE THREAD

**Issue by fanatid** [mafintosh/prebuild#159]
Sorry, but can you clarify, what advantages has this package compared to [node-pre-gyp](https://www.npmjs.com/package/node-pre-gyp).
Thank you.

**Comment by piranna** [comment]
Use of free github releases to publish prebuild images instead of paid Amazon S3 instances and easier usage.

**Comment by fanatid** [comment]
I seen this, but `node-pre-gyp` also supports github as host, not sure how well it works. Anything else?

**Comment by fanatid** [comment]
Anyway, thank you @piranna

**Comment by ralphtheninja** [comment]
@fanatid they both solve the same use case but main advantages using prebuild (imo) are

* downloaded binaries are cached in `~/.npm/_prebuilds`
* support for electron
* builds for all targets you want to support in one go
* creates a github release for you and adds the binaries to it
