### ISSUE TITLE
switch from request to simple-get

### ISSUE THREAD

**Issue by ralphtheninja** [mafintosh/prebuild#17]

**Comment by mafintosh** [comment]
Fixed in latest release although it seems node-gyp requires request as well *sigh*. We should send a PR to node-gyp as to switch it to simple-get.

**Comment by ralphtheninja** [comment]
![63047343](https://cloud.githubusercontent.com/assets/308049/9022399/3aee98dc-3874-11e5-8d2c-744ba2548ac8.jpg)
