### ISSUE TITLE
Exclude Node 0.10 and 0.12 from --all

### ISSUE THREAD

**Issue by mourner** [mafintosh/prebuild#176]
Node v0.10.* and v0.12.* are [at End of Life](https://github.com/nodejs/LTS), meaning that they're not maintained and insecure, and there's no need to build modules for these versions today by default. 

So I'd suggest filtering them out from the list of versions used with `--all` switch. People that need to build for legacy Node versions can always use the `-t` switch.

**Comment by ralphtheninja** [comment]
prebuild uses `supportedTargets` from `node-abi` here https://github.com/lgeiger/node-abi/blob/7d1b903eaf2337b342fb9fd6511f625f50bd8a35/index.js#L66-L67 .. maybe they should be removed from node-abi instead? cc @lgeiger

**Comment by lgeiger** [comment]
👍  on this change!

0.10 and 0.12 are only part of `supportedTargets` because of prebuild.

**Comment by mourner** [comment]
Awesome, thank you @ralphtheninja!
