### ISSUE TITLE
fails if /root/.npm does not exist

### ISSUE THREAD

**Issue by maxogden** [mafintosh/prebuild#21]
```
prebuild WARN install ENOENT, open '/root/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.4.1-leveldown-v1.4.1-node-v14-linux-ia32.tar.gz.440-20f6a8e.tmp'
```

running with `--unsafe-perm` fixed it, but it shouldn't fail in this case

**Comment by ralphtheninja** [comment]
What exactly is failing? Does download fail and then fallback to compile?

**Comment by ralphtheninja** [comment]
@maxogden ping :)

**Comment by maxogden** [comment]
@ralphtheninja sorry found this with @mafintosh and he said to open an issue and has an idea for a fix I think

**Comment by ralphtheninja** [comment]
Ok. Well I just wanted to clarify what was the actual problem. I couldn't manage to reproduce it myself.

**Comment by mafintosh** [comment]
ah yes. the issue is that the `~/.npm` folder does not exist the first time you run npm on a machine (we hit this inside a vm).

**Comment by ralphtheninja** [comment]
@mafintosh So you should be able to reproduce it by simply deleting `~/.npm`?

**Comment by ralphtheninja** [comment]
Is this still an issue? Let me know and I'll fix it straight away.
