### ISSUE TITLE
add --no-compile flag when downloading

### ISSUE THREAD

**Issue by mafintosh** [mafintosh/prebuild#27]
we should support a `--no-compile` flag when using `--download`. this would allow someone to have a js fallback for a native dependency and never having to compile anything.

**Comment by mafintosh** [comment]
would be super useful for native optionalDependencies

**Comment by ralphtheninja** [comment]
:+1: 

Do you have any examples of modules that could use this straight out of the box?

**Comment by mafintosh** [comment]
Yes. The native dependencies of [ws](https://github.com/websockets/ws) (https://github.com/feross/bittorrent-tracker/issues/92). They all have pure js fallbacks

**Comment by ralphtheninja** [comment]
Hmm, can't we just do `--compile false`? :)

**Comment by mafintosh** [comment]
That should the same in minimist terms
