### ISSUE TITLE
Developing native modules while using prebuild and avoiding making devs grumpy!

### ISSUE THREAD

**Issue by ralphtheninja** [mafintosh/prebuild#33]
What can we do to make it easy to use prebuild for devs while developing modules? Obviously they don't want to download a prebuilt `.tar.gz` file while developing, they want to compile and it should be simple to do that.

See @rvagg 's comment here https://github.com/justmoon/node-bignum/pull/60#issuecomment-138393646

cc @mafintosh

**Comment by brett19** [comment]
Whenever I am developing locally, I do not use `npm install` on a folder, as that invokes the entirety of npm's wrath.  I usually use node-gyp directly.  What is the typical use-case of a developer that you are trying to make easier here?

**Comment by ralphtheninja** [comment]
@brett19 Using `node-gyp` directly makes sense to me as well

**Comment by mafintosh** [comment]
I also use node-gyp directly

**Comment by ralphtheninja** [comment]
> as that invokes the entirety of npm's wrath

lol
