### ISSUE TITLE
Update node-gyp to 3.0

### ISSUE THREAD

**Issue by ralphtheninja** [mafintosh/prebuild#34]
And use that to install headers as well.

**Comment by ralphtheninja** [comment]
This should solve problems when trying to build for node 4.0.0

**Comment by mafintosh** [comment]
:+1:

**Comment by ralphtheninja** [comment]
It's no bug anymore since https://github.com/mafintosh/node-gyp-install/commit/f954f056a44829f08fb27e6b95a7ef098c5d4066 was fixed

I'll test around a bit with the new `node-gyp` to see if it works well.
