### ISSUE TITLE
Support for http proxy

### ISSUE THREAD

**Issue by appelgriebsch** [mafintosh/prebuild#35]
Downloading prebuild binaries failed when sitting behind an HTTP proxy. The tool should take the environment variable HTTP_PROXY or HTTPS_PROXY into account when accessing the Internet.

**Comment by ralphtheninja** [comment]
`prebuild` uses [`simple-get`](https://github.com/feross/simple-get/blob/master/index.js). So I guess either we change to use something else or update simple-get to support this.

**Comment by ralphtheninja** [comment]
@mafintosh Since `simple-get` does `protocol.request()` [here](https://github.com/feross/simple-get/blob/master/index.js#L30). Is there any way we could get proxy functionality from `{http,https}.request()`?

**Comment by ralphtheninja** [comment]
@appelgriebsch What is the format of these environment variables? `host:port`?

**Comment by appelgriebsch** [comment]
@ralphtheninja the format of those environment variables are user:pwd@host:port. I saw in the node.js doc that you can handle HTTP request via proxy by sending an HTTP request to the proxy url with the original request url as path: 

{
  host: 'proxy.mydomain.com',
  port: '81',
  path: 'http://www.google.com'
}

**Comment by ralphtheninja** [comment]
@appelgriebsch I'd like to take a stab at this the coming days and might need some help testing things. Are you around? :)

**Comment by ralphtheninja** [comment]
Related issue https://github.com/Level/leveldown/issues/226

**Comment by brett19** [comment]
I did a bunch of research on this topic and built a pull-request for this, but only one portion of the PR ended up going in.  Anyone remember what happened to it (or my comments on it for that matter)?

**Comment by ralphtheninja** [comment]
@brett19 All I remember is that it was incomplete :) We should just bite the bullet and use `request`, since `node-gyp` uses that anyway we get it "for free".

**Comment by brett19** [comment]
That's why I wanted to find the notes I had written on this.  Specifically, I had implemented prebuild to using the `request` module, but ran into a significant number of issues with that...  Something to do with some magic inside of prebuild.

**Comment by brett19** [comment]
After a bit of thought, the issue was that I was trying to avoid changing too much code, and ran into issues where the data from the http request was being sent to two different streams, but the pump library couldn't handle the stream returned by request.  If the whole section of the download code was rewritten, it would likely be fine now though, especially since we don't even write the stream to two palces anymore.

**Comment by ralphtheninja** [comment]
> After a bit of thought, the issue was that I was trying to avoid changing too much code, and ran into issues where the data from the http request was being sent to two different streams, but the pump library couldn't handle the stream returned by request

Oh right. `request` can be a pain in the butt when you want to stream stuff.

**Comment by ralphtheninja** [comment]
Maybe we could add proxy support to `simple-get` or maybe get that into `hyperquest`

**Comment by ralphtheninja** [comment]
I'd like to use [got](https://github.com/sindresorhus/got/tree/v5.x) for this. Maybe get some time this week to make a PR for it.

**Comment by csulok** [comment]
+1 

We ran into this just today, when trying to install leveldown behind a corporate proxy/firewall (MS TMG) and it appears the npm set http_proxy / https_proxy is honored throughout an installation, except with prebuild. 

Currently trying to work around it by manually "warming the cache"

**Comment by gaving** [comment]
This ruined my day.

Currently hacking simple-get proxy details to get around the issue.

**Comment by lgeiger** [comment]
Downloading is now handled by [`prebuild-install`](https://github.com/mafintosh/prebuild-install).

It also supports http proxy.
