### ISSUE TITLE
Prebuild with a scoped module

### ISSUE THREAD

**Issue by corbinu** [mafintosh/prebuild#36]
Hello,

I am trying to set up prebuild with a scoped version of couchnode

My repo is here:  https://github.com/corbinu/couchnode

I have run into two issues. 

The first is an error when first running prebuilt I get
```

prebuild info build Packing build/Release/couchbase_impl.node into prebuilds/@corbinu/couchbase-v2.1.7-node-v46-darwin-x64.tar.gz
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'prebuilds/@corbinu/couchbase-v2.1.7-node-v46-darwin-x64.tar.gz'
    at Error (native)
```

I worked around this my manually creating the directory "@corbinu"

I then uploaded a release and the download link was wrong

```
prebuild --download
prebuild http request GET https://github.com/corbinu/couchnode/releases/download/v2.1.7/@corbinu/couchbase-v2.1.7-node-v46-darwin-x64.tar.gz
prebuild http 404 https://github.com/corbinu/couchnode/releases/download/v2.1.7/@corbinu/couchbase-v2.1.7-node-v46-darwin-x64.tar.gz
```
I also managed to work around this but would be nice if usage with scoped modules was provided out of the box

Thanks!

**Comment by ralphtheninja** [comment]
+1

**Comment by ralphtheninja** [comment]
I think the simplest solution would be to replace `'/'` with `'-'` when picking the module name from package.json

cc @mafintosh

**Comment by mafintosh** [comment]
@ralphtheninja either that or `mkdirp` the parent folder

**Comment by ralphtheninja** [comment]
Or actually, how about just replacing `'@scoped/package'` with `'package'`? Since the scoped things are only important when actually publishing to npm.

**Comment by mafintosh** [comment]
i don't think that'll work since `@foo/module` will clash with `@bar/module`

**Comment by ralphtheninja** [comment]
Sure, but where does that matter?

**Comment by ralphtheninja** [comment]
@mafintosh oh when downloading and caching it, nevermind.

**Comment by ralphtheninja** [comment]
https://github.com/mafintosh/prebuild/pull/43
