### ISSUE TITLE
how do you develop

### ISSUE THREAD

**Issue by juliangruber** [mafintosh/prebuild#67]
could be nice to add docs how a developer working on prebuild itself is testing her setup, maybe even with an example project

**Comment by ralphtheninja** [comment]
+1

**Comment by ralphtheninja** [comment]
@juliangruber We could add leveldown as a devDependency and build upon that?

**Comment by juliangruber** [comment]
you still need your own fork for uploading to github, right?

**Comment by ralphtheninja** [comment]
> you still need your own fork for uploading to github, right?

Aye.

Anything in particular you find awkward/unclear that needs to be improved?

**Comment by juliangruber** [comment]
i think i got it now, just a note like "to work on this project simply fork one of the binary modules already using it (like leveldown) and `npm link` prebuild into it" would do, right?

**Comment by ralphtheninja** [comment]
> i think i got it now, just a note like "to work on this project simply fork one of the binary modules already using it (like leveldown) and npm link prebuild into it" would do, right?

Yes. Maybe in form av a bulleted/numbered list: 1. create github token, 2. ...
