### ISSUE TITLE
prebuild issue with npm install leveldb (leveldb@0.7.1 preinstall)/Windows 7

### ISSUE THREAD

**Issue by lorymole** [mafintosh/prebuild#78]
Hi,

I'm running into an issue installing leveldb on windows.
The leveldb experts suggested I log an issue here.

thanks,

-Lory

Details below:

--------------------------------------------------------------------

% npm install leveldb

WARN engine leveldb@0.7.1: wanted: {"node":">=0.6.13 <0.9.0"} (current: {"node":"4.2.4","npm":"3.5.3"})
WARN engine leveldb@0.7.1: wanted: {"node":">=0.6.13 <0.9.0"} (current: {"node":"4.2.4","npm":"3.5.3"})
'make' is not recognized as an internal or external command,
operable program or batch file.
npm WARN enoent ENOENT: no such file or directory, open 'c:\lmolesky\REST\express\nodecellar\node_modules\d\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'c:\lmolesky\REST\express\nodecellar\node_modules\es5-ext\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'c:\lmolesky\REST\express\nodecellar\node_modules\es6-iterator\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'c:\lmolesky\REST\express\nodecellar\node_modules\es6-symbol\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'c:\lmolesky\REST\express\nodecellar\node_modules\express\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'c:\lmolesky\REST\express\nodecellar\node_modules\gyp\package.json'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lmolesky.ORADEV\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "leveldb"
npm ERR! node v4.2.4
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! leveldb@0.7.1 preinstall: `make build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldb@0.7.1 preinstall script 'make build'.

**Comment by ralphtheninja** [comment]
This has nothing to do with prebuild.

**Comment by ralphtheninja** [comment]
`leveldb` is no longer maintained, so you might want to use `level` instead, see https://github.com/level/level

**Comment by brett19** [comment]
@lorymole,
For the record, the error you were receiving was due to lack of build-tools being installed on your system.  Go take a look at the `node-gyp` system requirements for more information.
Cheers, Brett

**Comment by lorymole** [comment]
Thanks - looking deeper, I found that the problem was that a url
was hardwired to a specific port, which our firewall couldn'd deal with.
Once out of the firewall, I got it to install properly.

-Lory
