### ISSUE TITLE
Does prebuild do any bundling/static linking of libs?

### ISSUE THREAD

**Issue by rgbkrk** [mafintosh/prebuild#81]
Wondering if, for our use in [`zmq-prebuilt`](https://github.com/nteract/zmq-prebuilt) if we have to bundle a built libzmq as well.

**Comment by ralphtheninja** [comment]
It doesn't do any bundling of external dependencies. Only grabs the resulting `foo.node` file and creates a `.tar.gz` out of it.

**Comment by ralphtheninja** [comment]
I guess the easiest way would be to link statically with whatever external dependencies you need for your module.
