### ISSUE TITLE
Problem: io.js versions aren't on nodejs.org

### ISSUE THREAD

**Issue by hintjens** [mafintosh/prebuild#82]
E.g. if I try to build --all, it fails with 

```
404 response downloading http://nodejs.org/dist/v1.0.4/iojs-v1.0.4.tar.gz
```

Same for many of the targets in targets.js.

**Comment by mafintosh** [comment]
@ralphtheninja do you know o/ is failing?

**Comment by ralphtheninja** [comment]
@hintjens First, can you make sure you're using the latest version of prebuild? This should be handled by node-gyp@3

**Comment by hintjens** [comment]
```
nodejs> npm list -g prebuild
/home/ph/.nvm/v5.5.0/lib
└── prebuild@2.9.1 
```

**Comment by hintjens** [comment]
```
nodejs> npm list -g node-gyp
/home/ph/.nvm/v5.5.0/lib
├── node-gyp@3.2.1 
├─┬ npm@3.3.12
│ └── node-gyp@3.0.3 
└─┬ prebuild@2.9.1
  └── node-gyp@3.2.1 
```

**Comment by ralphtheninja** [comment]
I just tried this on `leveldown` and it works here:

![prebuild-iojs](https://cloud.githubusercontent.com/assets/308049/12953184/9c5d1124-d019-11e5-8831-720f556d773f.png)

So there's something fishy.

What does `prebuild --version` give you?

@hintjens You can ping me on freenode if you don't like having conversations on github :)

**Comment by hintjens** [comment]
```
nodejs> prebuild --version
2.9.1
```

I've installed everything over the last few days. Node 5.5.0.

I'm going to re-try using Node 5.1.0. (We should continue here rather than irc, thank you.)

**Comment by hintjens** [comment]
With Node 5.1.0 the result is the same:

```
nodejs> prebuild --all
prebuild info begin Prebuild version 2.9.1
prebuild info build Preparing to prebuild zyre@0.0.4 for v0.10.41 on linux-x64
prebuild info build prebuilds/zyre-v0.0.4-node-v11-linux-x64.tar.gz exists, skipping build
prebuild info build Preparing to prebuild zyre@0.0.4 for v0.12.9 on linux-x64
prebuild info build prebuilds/zyre-v0.0.4-node-v14-linux-x64.tar.gz exists, skipping build
prebuild info build Preparing to prebuild zyre@0.0.4 for v1.0.4 on linux-x64
gyp http GET http://nodejs.org/dist/v1.0.4/iojs-v1.0.4.tar.gz
gyp http 404 http://nodejs.org/dist/v1.0.4/iojs-v1.0.4.tar.gz
gyp WARN install got an error, rolling back install
prebuild ERR! install error 
prebuild ERR! stack Error: 404 response downloading http://nodejs.org/dist/v1.0.4/iojs-v1.0.4.tar.gz
prebuild ERR! stack     at Request.<anonymous> (/home/ph/.nvm/v5.1.0/lib/node_modules/prebuild/node_modules/node-gyp/lib/install.js:244:14)
prebuild ERR! stack     at emitOne (events.js:82:20)
prebuild ERR! stack     at Request.emit (events.js:169:7)
prebuild ERR! stack     at Request.onRequestResponse (/home/ph/.nvm/v5.1.0/lib/node_modules/prebuild/node_modules/request/request.js:952:10)
prebuild ERR! stack     at emitOne (events.js:77:13)
prebuild ERR! stack     at ClientRequest.emit (events.js:169:7)
prebuild ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:421:21)
prebuild ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
prebuild ERR! stack     at Socket.socketOnData (_http_client.js:311:20)
prebuild ERR! stack     at emitOne (events.js:77:13)
prebuild ERR! not ok 
prebuild ERR! build 404 response downloading http://nodejs.org/dist/v1.0.4/iojs-v1.0.4.tar.gz
```

**Comment by hintjens** [comment]
BTW, nice job with `leveldown`, I'm using it as inspiration for the Zyre binding.

**Comment by ralphtheninja** [comment]
Ok, you are indeed running the latest prebuild and for some reason it uses an older version of node-gyp.

> BTW, nice job with leveldown, I'm using it as inspiration for the Zyre binding.

I can't take any credit for that. That's @rvagg :)

**Comment by ralphtheninja** [comment]
Maybe try:

1. npm remove node-gyp -g
2. npm remove prebuild -g
3. npm i prebuild -g
4. rm ~/.npm -rf
5. rm ~/.node-gyp -rf

**Comment by hintjens** [comment]
Sorry for the slow turnaround. Did all that, and... same result:

```
nodejs> prebuild --all
prebuild info begin Prebuild version 2.9.1
prebuild info build Preparing to prebuild zyre@0.0.4 for v0.10.41 on linux-x64
gyp http GET http://nodejs.org/dist/v0.10.41/node-v0.10.41.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.41/node-v0.10.41.tar.gz
gyp http GET http://nodejs.org/dist/v0.10.41/SHASUMS256.txt
gyp http 200 http://nodejs.org/dist/v0.10.41/SHASUMS256.txt
prebuild info build prebuilds/zyre-v0.0.4-node-v11-linux-x64.tar.gz exists, skipping build
prebuild info build Preparing to prebuild zyre@0.0.4 for v0.12.9 on linux-x64
gyp http GET http://nodejs.org/dist/v0.12.9/node-v0.12.9.tar.gz
gyp http 200 http://nodejs.org/dist/v0.12.9/node-v0.12.9.tar.gz
gyp http GET http://nodejs.org/dist/v0.12.9/SHASUMS256.txt
gyp http 200 http://nodejs.org/dist/v0.12.9/SHASUMS256.txt
prebuild info build prebuilds/zyre-v0.0.4-node-v14-linux-x64.tar.gz exists, skipping build
prebuild info build Preparing to prebuild zyre@0.0.4 for v1.0.4 on linux-x64
gyp http GET http://nodejs.org/dist/v1.0.4/iojs-v1.0.4.tar.gz
gyp http 404 http://nodejs.org/dist/v1.0.4/iojs-v1.0.4.tar.gz
gyp WARN install got an error, rolling back install
prebuild ERR! install error 
prebuild ERR! stack Error: 404 response downloading http://nodejs.org/dist/v1.0.4/iojs-v1.0.4.tar.gz
prebuild ERR! stack     at Request.<anonymous> (/home/ph/.nvm/v5.1.0/lib/node_modules/prebuild/node_modules/node-gyp/lib/install.js:244:14)
prebuild ERR! stack     at emitOne (events.js:82:20)
prebuild ERR! stack     at Request.emit (events.js:169:7)
prebuild ERR! stack     at Request.onRequestResponse (/home/ph/.nvm/v5.1.0/lib/node_modules/prebuild/node_modules/request/request.js:952:10)
prebuild ERR! stack     at emitOne (events.js:77:13)
prebuild ERR! stack     at ClientRequest.emit (events.js:169:7)
prebuild ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:421:21)
prebuild ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
prebuild ERR! stack     at Socket.socketOnData (_http_client.js:311:20)
prebuild ERR! stack     at emitOne (events.js:77:13)
prebuild ERR! stack     at Socket.emit (events.js:169:7)
prebuild ERR! not ok 
prebuild ERR! build 404 response downloading http://nodejs.org/dist/v1.0.4/iojs-v1.0.4.tar.gz
```

Can I debug this myself? How can I tell what version of node-gyp we're using?

I'm using nvm, maybe that is affecting things.

**Comment by ralphtheninja** [comment]
What's the output of:

```
$ which node-gyp
$ node-gyp -v
$ env
```

**Comment by ralphtheninja** [comment]
@hintjens You could also check the version of `/home/ph/.nvm/v5.1.0/lib/node_modules/prebuild/node_modules/node-gyp/package.json` and if that is something like `3.2.1` this is probably a bug in `node-gyp` that we haven't caught before.

Worst case scenario is opening up `/home/ph/.nvm/v5.1.0/lib/node_modules/prebuild/node_modules/node-gyp/lib/install.js` at row `244` and debug the url value.

**Comment by ralphtheninja** [comment]
In `node-gyp@3.2.1` `install.js` should look something like:

```js
req.on('response', function (res) {                                              
  if (res.statusCode !== 200) {                                                  
    badDownload = true                                                           
    cb(new Error(res.statusCode + ' response downloading ' + release.tarballUrl))
    return                                                                       
  }                                                                              
  // content checksum                                                            
  getContentSha(res, function (_, checksum) {                                    
    var filename = path.basename(release.tarballUrl).trim()                      
    contentShasums[filename] = checksum                                          
    log.verbose('content checksum', filename, checksum)                          
  })                                                                             
                                                                                 
  // start unzipping and untaring                                                
  req.pipe(gunzip).pipe(extracter)                                               
})                                                                               
```

So would be interesting to see how `release.tarballUrl` get its value.

**Comment by ralphtheninja** [comment]
Maybe related issue? https://github.com/nodejs/node-gyp/issues/787

**Comment by hintjens** [comment]
Here's the output:

```
nodejs> which node-gyp
nodejs> node-gyp -v
The program 'node-gyp' is currently not installed. You can install it by typing:
sudo apt-get install node-gyp
nodejs> npm install -g node-gyp
...
nodejs> which node-gyp
/home/ph/.nvm/v5.1.0/bin/node-gyp
nodejs> node-gyp -v
v3.2.1
nodejs> env
NVM_PATH=/home/ph/.nvm/v5.1.0/lib/node
PATH=/home/ph/.nvm/v5.1.0/bin:/home/ph/perl5/bin:/home/ph/perl5/bin:/home/ph/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ph/android-ndk-r10e:/home/ph/android-sdk/platform-tools/:/home/ph/android-sdk/bin
...
prebuild ERR! build 404 response downloading http://nodejs.org/dist/v1.0.4/iojs-v1.0.4.tar.gz
```

**Comment by hintjens** [comment]
The version in /home/ph/.nvm/v5.1.0/lib/node_modules/prebuild/node_modules/node-gyp/package.json is  3.2.1.

**Comment by hintjens** [comment]
I can debug node-gyp, except I think prebuild is hiding its output.

There's `node_modules/npm/node_modules/node-gyp/lib/process-release.js` which calculates `tarballUrl` and I can debug it, if my console.log()s would show up. Any hints for that?

**Comment by hintjens** [comment]
OK, found the culprit, I think.

Someone is setting NVM_NODEJS_ORG_MIRROR, and when that is set, node-gyp ignores the carefully calculated URL from process-release.js.

So, `export NVM_NODEJS_ORG_MIRROR=` before running prebuild. Possibly worth documenting since it's such a cryptic problem.

**Comment by hintjens** [comment]
Thanks for all the help, @ralphtheninja!

**Comment by hintjens** [comment]
It works: https://github.com/hintjens/zyre-nodejs/releases

:-1:

**Comment by ralphtheninja** [comment]
> Thanks for all the help, @ralphtheninja!

![20160210_221438](https://cloud.githubusercontent.com/assets/308049/12962048/f1ab5bb6-d043-11e5-8547-bcdd5fe1d2dd.jpg)

My pleasure Pieter :)

**Comment by ralphtheninja** [comment]
> So, export NVM_NODEJS_ORG_MIRROR= before running prebuild. Possibly worth documenting since it's such a cryptic problem.

Ok, so it's nvm related thing. I'll write something on prebuild for future references. I personally use [n](https://github.com/tj/n)

**Comment by ralphtheninja** [comment]
> It works: https://github.com/hintjens/zyre-nodejs/releases
> 
> :+1:

Nice! Ping me if you need help building for windows (assuming it can build for windows). Also, @mafintosh and @juliangruber should be able to build for darwin.

**Comment by hintjens** [comment]
Thanks. I've got some internals to clean up first... bringing all
dependencies into node-gyp rather than using autotools to build them as we
do now.

On Wed, Feb 10, 2016 at 10:37 PM, Lars-Magnus Skog <notifications@github.com

**Comment by rvagg** [comment]
fwiw I'm going to be proposing a switch from `NVM_NODEJS_ORG_MIRROR` to `NODEJS_ORG_MIRROR` or `NODE_GYP_MIRROR` or something just as ugly in node-gyp soon (thanks for the reminder). It was introduced in node-gyp because users in China needed a way to do this and were already using that var for nvm, but we've got ourselves in trouble relying on it since it's really intended to be an internal nvm thing and causes side effects like this one.

**Comment by mafintosh** [comment]
@rvagg if we hosted the io.js headers on the node.js website this would also be fixed right? is that a no-go?

**Comment by rvagg** [comment]
no, probably not going to happen, we really just need people to move to Node v4+ as all io.js lines are completely unsupported now

**Comment by hintjens** [comment]
It might be worth changing the defaults in prebuild then, so that by
default it builds only for Node v4+.
