### ISSUE TITLE
delete @#%@#@ nvm environment variables when prebuilding ;)

### ISSUE THREAD

**Issue by ralphtheninja** [mafintosh/prebuild#84]
See this thread https://github.com/mafintosh/prebuild/issues/82

Apparently, if you use nvm, [these environment variables](https://github.com/nodejs/node-gyp/blob/master/lib/process-release.js#L51-L56) might be set, which messes up the download url for `node-gyp`.

I propose we simply DELETE them when doing prebuilds.

**Comment by juliangruber** [comment]
+1

**Comment by mafintosh** [comment]
+1

**Comment by ralphtheninja** [comment]
Just to be clear. This is not at all related to `prebuild`. I guess we could just do:

```js
delete process.env.NVM_IOJS_ORG_MIRROR
delete process.env.NVM_NODEJS_ORG_MIRROR
```

At a suitable location

**Comment by juliangruber** [comment]
only when prebuild isn't used as a lib, so it should be in the bin.js

**Comment by ralphtheninja** [comment]
> only when prebuild isn't used as a lib, so it should be in the bin.js

Yeah ok. Should we delete them both during `build` and `prebuild`? Like, if we are installing and there are no prebuilt binaries, then we would get the same error.

**Comment by ralphtheninja** [comment]
2.9.2
