### ISSUE TITLE
Problem: lodash.padright is deprecated

### ISSUE THREAD

**Issue by hintjens** [mafintosh/prebuild#87]
Installing prebuild gives this error (which I think is new):

```
npm WARN deprecated lodash.padright@3.1.1: This package has been renamed. Use lodash.padend@^4.0.0.
```

**Comment by mafintosh** [comment]
its a dependency of npmlog called gauge that apparently uses this (npm ls). i opened an issue there to get them to fix it

**Comment by hintjens** [comment]
OK, closing here. Cheers!
