### ISSUE TITLE
Problem: prebuild --all can be *slow*

### ISSUE THREAD

**Issue by hintjens** [mafintosh/prebuild#89]
In my project I've a binding.cc that depends on a C/C++ project.gyp, which depends on a further project.gyp, and this on a 3rd one. Each of these builds a static library.

`prebuild --all`, recompiles every source, every time. It's not necessary as only the binding.cc uses V8. Is there a way to tell prebuild, "don't rebuild this dependency if it's already been done?"

**Comment by mafintosh** [comment]
i think we use `node-gyp rebuild` to build as that's the "safest" one. i'd have no problem adding a flag that would use `node-gyp build` instead though to support incremental builds. maybe `--no-rebuild`? @juliangruber @ralphtheninja thoughts?

**Comment by hintjens** [comment]
Sounds like a good solution. I'd suggest "--incremental" as a switch (keep it positive:)

**Comment by ralphtheninja** [comment]
I have no problem with that either as long as we can have a good api for it

**Comment by ralphtheninja** [comment]
> Sounds like a good solution. I'd suggest "--incremental" as a switch (keep it positive:)

`--incremental` sounds good

**Comment by ralphtheninja** [comment]
I'll get that fixed today. Need to walk the dog first :)

**Comment by hintjens** [comment]
Awesome, thanks... I'd send a PR but would mess it up :)

**Comment by ralphtheninja** [comment]
So I guess instead of doing `node-gyp rebuild` we would do `node-gyp configure build`.

@hintjens Are you sure your `binding.cc` is touched properly so it will be compiled?

**Comment by ralphtheninja** [comment]
@hintjens I could push this as a branch and you could try it locally, by cloning this repo and doing `npm link` inside it. That way we could try it out "in the wild" before releasing it. It's probably easier if you try it on your machine.

**Comment by ralphtheninja** [comment]
https://github.com/mafintosh/prebuild/tree/incremental-builds

Once this works fine, I'll update with tests and docs and make a proper PR.

**Comment by ralphtheninja** [comment]
The commit is here https://github.com/mafintosh/prebuild/commit/c6b0010c1ebe97775a5a3ad53bc4ac51991478ef

**Comment by ralphtheninja** [comment]
@hintjens If your `binding.cc` is not compiled you can do

```
$ prebuild --all --preinstall <script> --incremental
```

`<script>` in this case will be executed before build, so you could do something like `touch binding.cc` there. Just a heads up.

**Comment by hintjens** [comment]
@ralphtheninja sorry, was making food for my kids. Am back now and will test your patch.

**Comment by hintjens** [comment]
So as far as I can tell (I don't know how to trace what prebuild is actually doing), --incremental allows prebuild to continue, if interrupted. However it recompiles all sources for each release (thus, still takes the same time). If I don't use --incremental, it'll restart from the beginning, if interrupted.

Once all releases are built, it skips the build the next time around. Doing `touch binding.cc` changes nothing here. Whereas, `node-gyp build` does detect that change, and compiles binding.cc.

**Comment by hintjens** [comment]
@ralphtheninja I'll investigate this, based on what you've already done.

**Comment by ralphtheninja** [comment]
> @ralphtheninja I'll investigate this, based on what you've already done.

Cool. Let me know how it goes and if we need to tweak things.

**Comment by brett19** [comment]
It would be cool if there was a way to point node-gyp to using a specific incremental folder so that each node-gyp version can be independently built incrementally.

**Comment by hintjens** [comment]
Yes, we can do this, I know how (I think). Disclaimer: I forked node-gyp to node-ninja so I can make improvements to it.

I'll add an option to node-ninja to let you specify the output directory (-Goutput_dir option to gyp). This is hardcoded as 'build' in node-gyp.

So with incremental builds we just create an output directory for each target ABI.

Sound good? 

(If this works I'll have a patch to prebuild to let it use node-ninja optionally.)

**Comment by hintjens** [comment]
Hang on... :) if we have a separate output directory for each node version, we can't collapse compile times. /me needs to play with this a little...

**Comment by ralphtheninja** [comment]
> (If this works I'll have a patch to prebuild to let it use node-ninja optionally.)

Patches welcome :)

**Comment by hintjens** [comment]
Randomish question, how does opts.gyp work?

**Comment by ralphtheninja** [comment]
> Randomish question, how does opts.gyp work?

I have no idea. In which context?

cc @mafintosh

**Comment by hintjens** [comment]
Afaics it's never set and if I pass --gyp=something on the command line it dies horribly.

Perhaps there's an IRC where I should ask this? It's kind of off-topic.

**Comment by hintjens** [comment]
OK, so I've pushed a PR with functionality to support `node-ninja`, which has an option to send builds to different directories. Now CI on `prebuild` dies horribly, and this stuff is new to me... can anyone tell me what I broke?

**Comment by ralphtheninja** [comment]
@hintjens Close this when you feel this is no longer an issue.

**Comment by hintjens** [comment]
I'll come back with a PR when I've got incremental builds working with node-ninja as backend. Since --incremental can't work with node-gyp, I suggest we delete that branch, and I'll use the changes as basis for a new commit.

**Comment by ralphtheninja** [comment]
> I suggest we delete that branch

It's gone
