### ISSUE TITLE
problems finding prebuilts for ubuntu and node 5.6.0

### ISSUE THREAD

**Issue by ralphtheninja** [mafintosh/prebuild#90]
See https://github.com/Level/leveldown/issues/254

Just linking this here for reference.

**Comment by juliangruber** [comment]
i don't see arm releases of leveldown, is that the problem?

**Comment by ralphtheninja** [comment]
> i don't see arm releases of leveldown, is that the problem?

Yep. I'll build them later today.

**Comment by ralphtheninja** [comment]
Closing, since it's not a bug. Just missing binaries.
